SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Area')
BEGIN

	PRINT 'Create table...'
	CREATE TABLE [dbo].[Area](
		[Area_Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
		[Region_Id] [int] NOT NULL,
		[Name_Area] [varchar](50) NOT NULL,
		[TS] [smalldatetime] NOT NULL DEFAULT (getdate()),
		[Code_Area] [varchar](5) NOT NULL,
		[Visible] [bit] NOT NULL DEFAULT ((1)),
	CONSTRAINT [PK_Area] PRIMARY KEY CLUSTERED 
	(
		[Area_Id] ASC
	)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
ELSE
BEGIN

	-- Атрибут активности записи, т.е. возможности использования в текущий момент
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Area' AND COLUMN_NAME = 'Visible')
		ALTER TABLE [Area] ADD [Visible] bit NOT NULL DEFAULT ((1));
	ELSE
	BEGIN
		IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Area' AND COLUMN_NAME = 'Visible' AND DATA_TYPE = 'bit' AND IS_NULLABLE = 'NO' AND COLUMN_DEFAULT = '((1))')
		BEGIN
			EXEC DropDefaultValue 'Area', 'Visible';
			ALTER TABLE Area ALTER COLUMN [Visible] bit NOT NULL;
			ALTER TABLE [Area] ADD CONSTRAINT DF_Area_Visible DEFAULT((1)) FOR [Visible];
		END
	END

END
GO

SET ANSI_PADDING OFF
GO